#!/bin/bash -e
#
# Uploads all java keystores to the certs container on silkmq-staging
#
# usage: sudo ./upload-jks


letsencryptdir=/etc/letsencrypt/live

user=$SUDO_USER
identityfile=$HOME/.ssh/id_rsa

remoteuser=$user
server=h04.apifocal.org
container=r-certs-nginx-1-3fdf4a93
remotedir=/usr/share/nginx/html

echo "Keystores to upload:"
find $letsencryptdir -name "*.jks" | \
  xargs tar cfv - -C $letsencryptdir -P --xform 's,.*/\([^/]\+\),\1,' --show-stored-names | \
  ssh -C -i "$identityfile" "$remoteuser@$server" \
     "docker exec $container find $remotedir -type f -delete ; \
      docker cp - $container:$remotedir/"

